# Generated by Django 6.0.3 on 2026-03-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de lançamento')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Capa')),
                ('trailer_url', models.URLField(blank=True, verbose_name='URL do trailer (YouTube embed)')),
                ('official_url', models.URLField(blank=True, verbose_name='Site oficial')),
                ('genres', models.ManyToManyField(blank=True, to='games.genre', verbose_name='Gêneros')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['title'],
            },
        ),
    ]
