# Generated by Django 6.0.3 on 2026-05-11 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_genre_options_alter_game_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_by', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogo jogado',
                'verbose_name_plural': 'Jogos jogados',
                'ordering': ['-played_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
